### ISSUE TITLE
better input level monitoring

### ISSUE THREAD

**Issue by IgnacioIrigaray** [ixd704/MT16Tracker#1]
hi! thanks for the code.

I think that input monitoring would be much better if the  peak value (or a vu meter) of each armed input is displayed on the LCD display.

will it be possible? 

regards

**Comment by ixd704** [comment]
It will if you code it.  My goal was to make it so others could expand on this unit.  If you download the virtual machine in the link, you will find that you have all of the source code available for the unit and an environment for building new components you can run on it.  I have not tried to compile and install new firmware on it as that was beyond what I was trying to do.  You can build new binaries that you can run on it with the currently installed firmware.

**Comment by IgnacioIrigaray** [comment]
After looking in gstreamer and discarding it (only 8 channels of capture and high cpu usage) the most easy way to do input level monitoring is modifying the asoud.conf in /etc/ with to gain access to the individual channels and monitor the level of each channel with the vumeter in arecord. 



The steps are;

telnet the tracker and gain root access

replace /etc/asound.conf with the content the attached asoundmod.txt file:
 
[asoundMod.TXT](https://github.com/ixd704/MT16Tracker/files/6026421/asoundMod.TXT)


then run; 

`alsactl restore`

to make each individual input accesible



turn on the ADC
`echo 1 > /sys/class/gpio/gpio47/value`

replace asound.conf (you can safely remove from the root filesystem as the original one reappear after reboot)

and finally 

`arecord -D plug:inchX -r 48000 -c 1 -f S16_LE -vv null`

where X is the channel number (1 to 16) and a lovely vumeter appears.

the integration with the menu tracker is the next step, but i can't compile the code yet.

hope this will be helpful.

**Comment by ixd704** [comment]
Did you download the VM?  It should compile everything for you.  The other option is to load up a USB connected drive with a build environment and let the tracker do the compiling which will also work.  You will have to copy the header files from the VM build environment.  Take a look at the history file and you should find everything required to do the cross compile.  If I remember correctly the sources are all buried in /opt directory (been a while since I looked at compiling anything).

**Comment by ixd704** [comment]
I am going to give your changes a go as you have peaked my interest :-)

**Comment by ixd704** [comment]
OK, so I see what you are doing.  The menu code would require a modification to either show the filename and disk usage or to show the VU meters.  The VM will allow you to recompile the menu code, but it comes with a caveat in that the current version has been modified to integrate with the web interface that was being developed.  So you will have to do some work to revert it to the current way it works.  

The other option is to just look at the current menu tree and add in your mods to the proto file and code and then re-enable the record and stop functions that are currently not appearing (I think they were in the middle of testing uploads and downloads to the website and remote control.  They have also installed a webserver on the tracker for remote controlling which I have some of the code for if you are interested.

**Comment by f-galland** [comment]
Ignacio, this looks interesting. Do you have the VM image somewhere? The links are dead here, it seems.

**Comment by ixd704** [comment]
Yes I had to move it as I ran out of storage space.  I will try to clean up my G drive and make it available again.


----- Original Message -----
From: f-galland ***@***.***)
Date: 07/27/22 10:15
To: ixd704/MT16Tracker ***@***.***)
Cc: Ian Douglas ***@***.***), Comment ***@***.***)
Subject: Re: [ixd704/MT16Tracker] better input level monitoring (#1)

Ignacio, this looks interesting. Do you have the VM image somewhere? The links are dead here, it seems.

**Comment by f-galland** [comment]
Great! Looking forward to that. I was losing hope!

**Comment by ixd704** [comment]
The VM is available here:
https://mega.nz/file/nYwzEAbC#bXCHMGGdTuczqBc49LXcGFnkZ_bV5l5mkDCCcxLkXP8
