### ISSUE TITLE
The link to the zip file with firmware 3.0.2 is dead

### ISSUE THREAD

**Issue by perpuder** [ixd704/MT16Tracker#3]
The Googledrive link with the zip file with firmware 3.0.2 is dead :(
I really want to upgrade the firmware. Stuck on 1.46

Thank you!

**Comment by ixd704** [comment]
Updated

Ian


----- Original Message -----
From: perpuder ***@***.***)
Date: 10/21/23 09:19
To: ixd704/MT16Tracker ***@***.***)
Cc: Subscribed ***@***.***)
Subject: [ixd704/MT16Tracker] The link to the zip file with firmware 3.0.2 is dead (Issue #3)

The Googledrive link with the zip file with firmware 3.0.2 is dead :(
I really want to upgrade the firmware. Stuck on 1.46

Thank you!

**Comment by ixd704** [comment]
File link fixed.
